---

dictionaries:
  - en

excluded_files:
  - "*.enc"
  - ".typo-ci.yml"
  - ".travis.yml"
  - "chefignore"
  - "Berksfile"
  - ".github/*"

excluded_words:
  - update-initramfs
  - setxkbmap
  - udevadm
  - xkboptions
  - timedatectl